import React from 'react'

function contact() {
  return (
    <div>
      Contact Page
    </div>
  )
}

export default contact

export const metadata = {
  title: "Contact Page",
  description: "Generated by create next app",
};